### ISSUE TITLE
Remote is incorrectly parsed when branch is having `/` in the name

### ISSUE THREAD

**Issue by vr00** [jasonmccreary/git-trim#15]
Hi there, we are using branch names with `/` because they group nicely in some git clients. I would love to use your package with remote repo but sadly it does not work 😢 

When running 
`git trim --merged --remote --dry-run`

The output is e.g. 
```bash
API-FEAT/APP-173-add-delete-offers-request will be deleted from origin/API-FEAT.
API-FIX/APP-188-handle-empty-fields-on-update-webhook will be deleted from origin/API-FIX.
```

And if run without `--dry-run` nothing happens. I assume it's because remote is incorrectly parsed `origin/API-FEAT` instead of only `origin`. Branch name is correct though.

Unfortunately I'm not proficient enough to fix it and submit a PR but I recon problem is on lines
https://github.com/jasonmccreary/git-trim/blob/main/git-trim#L156
https://github.com/jasonmccreary/git-trim/blob/main/git-trim#L187

EDIT:
I think replacing `${name%/*}` with `${name%%/*}` would do it 🤞 . Same for `${branch%/*}`. Test though 🙏

**Comment by jasonmccreary** [comment]
Sorry all. Notifications were turned off and didn't realize this hadn't been addressed.
