### ISSUE TITLE
Add option to dry running the commands

### ISSUE THREAD

**Issue by paptito** [jasonmccreary/git-trim#5]
It would be nice to have the option to dry running a command that only lists all affected branches.

Example with --list:

`git trim --merged --list`

**Comment by jasonmccreary** [comment]
@paptito, this was just added in #4. I'm going to leave it on `main` for additional testing before tagging. You're welcome to copy down the latest script to try it too. 👍

**Comment by mhdcodes** [comment]
I think this issue should be closed now. Since all work has been done including the documentation.

**Comment by jasonmccreary** [comment]
Yes, I just tagged 0.2.0.
