### ISSUE TITLE
Add how to update section to README

### ISSUE THREAD

**Issue by mhdcodes** [jasonmccreary/git-trim#6]
## Description

I think we need to a section to README. With instruction on how to update to the latest version.

When installed as NPM global package, It's simple as running `npm update -g git-trim`. 

But for the case of installing this package as `zsh` plugin, I think we need to add instructions to update: 

```sh
cd $ZSH_CUSTOM/plugins/git-trim && git fetch && git pull
```

**Comment by jasonmccreary** [comment]
Will do. I also need to add something about the new `--dry-run` option.

**Comment by jasonmccreary** [comment]
Updated.
