### ISSUE TITLE
Suggestion: Add package badges to README

### ISSUE THREAD

**Issue by mhdcodes** [jasonmccreary/git-trim#8]
## Description

I think it would be good to have some README badges:

- Install on NPM
[![NPM](https://nodei.co/npm/git-trim.png)](https://npmjs.org/package/git-trim)
[![NPM](https://nodei.co/npm/git-trim.png?mini=true)](https://npmjs.org/package/git-trim)

- Version
[![npm version](https://badge.fury.io/js/git-trim.svg)](https://badge.fury.io/js/git-trim)

- Contributors
[![contributors](https://img.shields.io/github/contributors/jasonmccreary/git-trim)](https://github.com/jasonmccreary/git-trim/graphs/contributors)

- Activity
[![Activity](https://img.shields.io/github/commit-activity/m/jasonmccreary/git-trim)](https://github.com/jasonmccreary/git-trim/pulse)

## Services

- https://nodei.co
- https://shields.io
- https://badge.fury.io/

**Comment by jasonmccreary** [comment]
As this nears "feature complete", I worry these badges may appear misleading as there would not be any activity. Also, wouldn't want people to think it was only an npm package at first glance.

**Comment by mhdcodes** [comment]
Fair enough. :+1:
